server:
  port: 8082
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/figurinedb?user=root
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect